version: '3.8'

services:
  app:
    build: .
    container_name: consommation
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./config:/var/www/html/config
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: consommation-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consommation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gestion-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: